name: CD

on:
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@uin-federation'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
        shell: bash

      - run: pnpm exec nx report --skip-nx-cache
        shell: bash

      - run: pnpm exec nx release publish --skip-nx-cache --access public
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
